dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

env:
  global:
    - DJF_USERNAME=postgres

install: travis_retry pip install coveralls tox-travis

script: tox

after_success: coveralls
